# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneme', models.CharField(max_length=128)),
                ('L', models.FloatField(default=0.0)),
                ('C', models.FloatField(default=0.0)),
                ('R', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AnchorSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_set_name', models.CharField(max_length=128, unique=True)),
                ('timestamp', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
                ('used', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
                ('saved_phonemes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GoldenSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=128, unique=True)),
                ('anchor_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.AnchorSet')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=128, unique=True)),
                ('phoneme', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.User'),
        ),
        migrations.AddField(
            model_name='goldenspeaker',
            name='source_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.SourceModel'),
        ),
        migrations.AddField(
            model_name='anchorset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.User'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='anchor_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.AnchorSet'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Recording'),
        ),
    ]
