# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='model_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
