# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20161122_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorset',
            name='sabr_model_path',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
