# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_anchorset_pitch_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorset',
            name='built',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
