# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0005_anchorset_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorset',
            name='saved_phonemes',
            field=models.CharField(max_length=400),
        ),
    ]
