# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0006_auto_20161202_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorset',
            name='built',
            field=models.CharField(max_length=128),
        ),
    ]
