# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0007_auto_20161205_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=128)),
                ('source_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.SourceModel')),
            ],
        ),
    ]
