# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0009_sourcemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcemodel',
            name='slug',
        ),
    ]
