# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0010_remove_sourcemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='slug',
            field=models.SlugField(default='defualt', unique=True),
            preserve_default=False,
        ),
    ]
