# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0011_sourcemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenspeaker',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
    ]
