# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0013_goldenspeaker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenspeaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.User'),
        ),
    ]
