# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0015_goldenspeaker_contained_utterance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenspeaker',
            name='contained_utterance',
            field=models.ManyToManyField(to='speech.Utterance'),
        ),
    ]
