# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0016_auto_20161215_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenspeaker',
            name='timestamp',
            field=models.CharField(default='1', max_length=128),
            preserve_default=False,
        ),
    ]
