# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0017_goldenspeaker_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorset',
            name='anchor_set_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='anchorset',
            name='slug',
            field=models.SlugField(),
        ),
    ]
