# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0018_auto_20170220_2311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anchorset',
            unique_together=set([('anchor_set_name', 'user')]),
        ),
    ]
