# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0019_auto_20170220_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenspeaker',
            name='status',
            field=models.CharField(default='synthesizing', max_length=128),
            preserve_default=False,
        ),
    ]
