# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0020_goldenspeaker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor',
            name='recording',
        ),
    ]
