# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0021_remove_anchor_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='anchor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='speech.Anchor'),
            preserve_default=False,
        ),
    ]
