# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0022_recording_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorset',
            name='modified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
