# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0025_goldenspeaker_aborted'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='week',
            field=models.CharField(default='week1', max_length=128),
            preserve_default=False,
        ),
    ]
