# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0026_utterance_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorset',
            name='saved_phonemes',
            field=models.CharField(max_length=1000),
        ),
    ]
