# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0027_auto_20170919_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenspeaker',
            name='tempo_scale',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
