# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0030_auto_20180124_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenspeaker',
            name='aborted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goldenspeaker',
            name='tempo_scale',
            field=models.FloatField(default=0.0),
        ),
    ]
