# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0031_auto_20180124_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorset',
            name='saved_phonemes',
            field=models.CharField(default='[""]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='goldenspeaker',
            name='select_phoneme_groups',
            field=models.CharField(default='[""]', max_length=1000),
        ),
    ]
