# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0032_auto_20180124_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorset',
            name='display',
            field=models.CharField(default='Phoneme', max_length=128),
        ),
    ]
