# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0033_anchorset_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchorset',
            name='pitch_path',
        ),
        migrations.RemoveField(
            model_name='anchorset',
            name='sabr_model_path',
        ),
        migrations.AddField(
            model_name='anchorset',
            name='cached_file_path',
            field=models.CharField(default='[""]', max_length=1000),
        ),
    ]
