# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0034_auto_20181018_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchorset',
            name='cached_file_path',
        ),
        migrations.AddField(
            model_name='recording',
            name='cached_file_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
