# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0035_auto_20181018_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorset',
            name='cached_file_dir',
            field=models.CharField(default='', max_length=128),
        ),
    ]
