# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0037_remove_anchorset_cached_file_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='cached_file_path',
        ),
        migrations.AddField(
            model_name='anchorset',
            name='cached_file_dir',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='anchorset',
            name='wav_file_dir',
            field=models.CharField(default='', max_length=128),
        ),
    ]
