# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0038_auto_20181018_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorset',
            name='pitch_model_dir',
            field=models.CharField(default='', max_length=128),
        ),
    ]
