# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0039_anchorset_pitch_model_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorset',
            name='pitch_model_built',
            field=models.CharField(default='False', max_length=128),
        ),
    ]
