# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-29 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0040_anchorset_pitch_model_built'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldenspeaker',
            name='select_phoneme_groups',
        ),
        migrations.RemoveField(
            model_name='goldenspeaker',
            name='tempo_scale',
        ),
        migrations.AddField(
            model_name='goldenspeaker',
            name='gmm_model_path',
            field=models.CharField(default='', max_length=128),
        ),
    ]
