# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0042_remove_anchorset_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='cached_file_dir',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='pitch_model_dir',
            field=models.CharField(default='', max_length=128),
        ),
    ]
