# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0043_auto_20181029_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchorset',
            name='pitch_model_dir',
        ),
    ]
