# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0046_auto_20181031_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='user',
        ),
        migrations.AddField(
            model_name='anchor',
            name='record_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
