# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0047_auto_20181101_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='phoneme',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='record_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
