# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0048_auto_20181101_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor',
            name='phoneme',
        ),
    ]
