# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-05 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0049_remove_anchor_phoneme'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenspeaker',
            name='output_wav_dir',
            field=models.CharField(default='', max_length=128),
        ),
    ]
