# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-16 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='textgrid_dir',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='wav_file_dir',
            field=models.CharField(default='', max_length=128),
        ),
    ]
