# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpd', '0002_auto_20190116_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transcription_dir',
            field=models.CharField(default='', max_length=128),
        ),
    ]
